### ISSUE TITLE
including binary in repository

### ISSUE THREAD

**Issue by MatusGuy** [Localtings/ALI#1]
🤨

**Comment by tue8** [comment]
for mopm!!!

**Comment by tue8** [comment]
unfortunately, mopm cant download binaries from releases

**Comment by tue8** [comment]
working on that

**Comment by tue8** [comment]
btw if you already have mopm please [update](https://localtings.github.io/mopm/) it :]
all versions < 0.2.0 are unusable since there're **REALLY** buggy

**Comment by MatusGuy** [comment]
> unfortunately, mopm cant download binaries from releases

I might be able to help you with that


if it had more than one file 😐

**Comment by tue8** [comment]
Ah, no need bro. Just got it fixed :trollface:
